<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GeoFinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="GeoFinal_files/libs/clipboard/clipboard.min.js"></script>
<script src="GeoFinal_files/libs/quarto-html/quarto.js"></script>
<script src="GeoFinal_files/libs/quarto-html/popper.min.js"></script>
<script src="GeoFinal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GeoFinal_files/libs/quarto-html/anchor.min.js"></script>
<link href="GeoFinal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GeoFinal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GeoFinal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GeoFinal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GeoFinal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GeoFinal</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="geo-data-and-methods-in-r" class="level2">
<h2 class="anchored" data-anchor-id="geo-data-and-methods-in-r">Geo-data and Methods in R:</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
|---------|---------|---------|---------|
=========================================
                                          </code></pre>
</div>
</div>
<section id="species-1-distribution-modelling" class="level3">
<h3 class="anchored" data-anchor-id="species-1-distribution-modelling"><strong>1: Species 1 Distribution Modelling</strong></h3>
<section id="the-task-run-linear-models-to-predict-the-present-day-distribution-of-species-1." class="level4">
<h4 class="anchored" data-anchor-id="the-task-run-linear-models-to-predict-the-present-day-distribution-of-species-1.">The task: run linear models to predict the present day distribution of species 1.</h4>
<p>Here, my chosen species 1 is: <em>Myzus persicae</em>, the green peach aphid.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Myzus%20persicae%20-01.jpg" class="img-fluid figure-img" alt="An image of Myzus persicae, the green peach aphid"></p>
<figcaption><em>Myzus persicae</em>, the green peach aphid.</figcaption>
</figure>
</div>
</section>
<section id="which-set-of-climatic-variables-best-explains-the-current-distribution-of-the-species" class="level4">
<h4 class="anchored" data-anchor-id="which-set-of-climatic-variables-best-explains-the-current-distribution-of-the-species"><u><em>Which set of climatic variables best explains the current distribution of the species?</em></u></h4>
<p>In order to run linear models to predict the present-day distribution of <em>M. persica</em>e, I had to first understand <em>which climate variables would be be important in predicting its distribution</em>.</p>
<p>In order to analyse this, I first generated a full model using all 19 bioclimatic variables that are included in the WorldClim Database. This full model would hopefully explain the data very well, but would likely to experience a lot of overfitting, due to the large quantity of variables it introduces. &nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/correlations-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Pairs of correlations between the BioClim data are difficult to interpret.</figcaption>
</figure>
</div>
</div>
</div>
<p>It was clear under testing that many of the bioclimatic variables are correlated. This is logically acceptable, as they are mostly underpinned by temperature- and precipitation- based metrics <span class="citation" data-cites="clim">(<a href="#ref-clim" role="doc-biblioref">Clim, n.d.</a>)</span>. However, the nature of their correlations was difficult to divine from the traditional plot, so I determined to derive a more contrived method.</p>
<p>In light of this, <u>I decided to use the following approach</u>:</p>
<p>i) I calculated the variance inflation factor (VIF) for each model, and removed the variable which demonstrated the most multi-colinearity (and would therefore be contributing to the overfitting problem the most)</p>
<p>ii) I then compared the Akaike Information Criteria (AIC) for each model. If the AIC had decreased (indicating lesser overfitting, and therefore a better model), I iterated the procedure. If the AIC increased (indicating that I had removed a variable that was highly important for the model to explain the observed data), then I put this variable back into the model, and considered it “safe”, for the remainder of my reduction procedure</p>
<p>iii) I continued this process until I had generated the lowest AIC possible, demonstrating the best fitting model with the least number of variables included.</p>
<p>This approach is partially limited, as it does not take into account the biological relevance of each variable. As such, future approaches might wish to rank the biological relevance of each of the 19 variables, and integrate this into a weighted system, alongside the statistical approach I employed, to generate the best explanatory model in light of both statistics and biology. However, this would rely on a great detail more research upon <em>M. persicae</em>, and it’s reliance upon bioclimatic variables, than has yet to be published. For example, whilst there is research on the effects of the minimum temperature of the coldest month <span class="citation" data-cites="odoherty1985">(<a href="#ref-odoherty1985" role="doc-biblioref">O’Doherty 1985</a>)</span>, and the temperature annual range <span class="citation" data-cites="alford2012">(<a href="#ref-alford2012" role="doc-biblioref">Alford 2012</a>)</span>; little else is available in the published literature.</p>
<p>Ultimately, the set of climatic variables that best explains the current distribution of <em>M. persicae</em>, according to my model, are:</p>
<p>i) the <strong>minimum temperature of the coldest month</strong> (bio6; which has already been shown to be biologically relevant <span class="citation" data-cites="odoherty1985">(<a href="#ref-odoherty1985" role="doc-biblioref">O’Doherty 1985</a>)</span>)</p>
<p>ii) the <strong>temperature annual range</strong> (bio7; which has also already been shown to be biologically relevant <span class="citation" data-cites="alford2012">(<a href="#ref-alford2012" role="doc-biblioref">Alford 2012</a>)</span>)</p>
<p>iii) the <strong>mean temperature of the wettest quarter</strong> (bio8)</p>
<p>iv) the <strong>mean temperature of the warmest quarter</strong> (bio10)</p>
<p>v) the <strong>precipitation of the driest month</strong> (bio14)</p>
<p>vi) the <strong>precipitation seasonality</strong> (bio15)</p>
<p>vii) the <strong>precipitation of the wettest quarter</strong> (bio16)</p>
<p>viii) the <strong>precipitation of the coldest quarter</strong> (bio19)</p>
<p>Whilst, according to my VIF calculations, some of these variables are still correlated, and there are also many variables included in the model (which reflects the complexity of biogeographical data), I believe that this approach demonstrates the best way of finding which climatic variables best explains the current distribution of <em>M. persicae</em>, with the current pre-existing literature. In order to generalise this to other species, it would be ideal for future researchers to generate a function, for the iteration of this approach, for the WorldClim variables.</p>
</section>
<section id="presenting-a-map-of-its-current-distribution" class="level4">
<h4 class="anchored" data-anchor-id="presenting-a-map-of-its-current-distribution"><u><em>Presenting a map of its current distribution:</em></u></h4>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/plottingP/Asp1-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Presence (yellow)/Absence (purple) model with red datapoints for M. persicae, across the European range.</figcaption>
</figure>
</div>
</div>
</div>
<p>My map of the current <em>M. persicae</em> distribution shows that the species is likely to be present in Eastern UK, North-West Scandinavia, Southern Greece and Italy, Northern and Southern France, Northern Germany, Poland, Lithuania, Latvia and Estonia; as well as diffusely around mainland Europe. Notably, <em>M. persicae</em> appears to be absent through most of the mainland, though. &nbsp;</p>
</section>
</section>
<section id="species-2-distribution-modelling" class="level3">
<h3 class="anchored" data-anchor-id="species-2-distribution-modelling"><strong>2: Species 2 Distribution Modelling</strong></h3>
<section id="the-task-run-linear-models-to-predict-the-present-day-distribution-of-species-2." class="level4">
<h4 class="anchored" data-anchor-id="the-task-run-linear-models-to-predict-the-present-day-distribution-of-species-2.">The task: run linear models to predict the present day distribution of species 2.</h4>
<p>Here, my chosen species 2 is: <em>Prunus persica</em>, the peach tree. I chose this because <em>M. persicae</em> is an aphid pest which feeds upon the peaches <span class="citation" data-cites="verdugo2016">(<a href="#ref-verdugo2016" role="doc-biblioref">Verdugo, 2016</a>)</span>; thus, their relative distributions are of interest.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Prunus%20persica-01.jpg" class="img-fluid figure-img" alt="An image of prunus persica, the peach tree."></p>
<figcaption><em>Prunus persica</em>, the peach tree.</figcaption>
</figure>
</div>
<p>Once again, in order to run linear models to predict the present-day distribution of <em>P. persica</em>, I had to first understand which climate variables would be be important in predicting its distribution. In order to analyse this I used the same method as described above, for continuity.</p>
<p>Here, I found that <u>the bioclimatic variables that best explains the current distribution of <em>P. persica</em>, according to my model, are</u>:</p>
<p>i) <strong>annual mean temperature</strong> (bio1)</p>
<p>ii) <strong>isothermality</strong> (bio3; which has already been established as biologically relevant: <span class="citation" data-cites="bielenberg2022">(<a href="#ref-bielenberg2022" role="doc-biblioref">Bielenberg 2022</a>)</span>)</p>
<p>iii) <strong>the temperature annual range</strong> (bio7)</p>
<p>iv) <strong>the mean temperature of the wettest quarter</strong> (bio8)</p>
<p>v) <strong>the mean temperature of the driest quarter</strong> (bio9)</p>
<p>vi) <strong>the mean temperature of the warmest quarter</strong> (bio10)</p>
<p>vii) <strong>the mean temperature of the coldest quarter</strong> (bio11; which has already been established as biologically relevant: <span class="citation" data-cites="bioscience2021">(<a href="#ref-bioscience2021" role="doc-biblioref">BIOSCIENCE 2021</a>)</span>)</p>
<p>viii) <strong>the annual precipitation</strong> (bio12; which has already been established as biologically relevant: <span class="citation" data-cites="ighbareyeh2019">(<a href="#ref-ighbareyeh2019" role="doc-biblioref">Ighbareyeh 2019</a>)</span>)</p>
<p>ix) <strong>the precipitation of the wettest month</strong> (bio13)</p>
<p>x) <strong>the precipitation seasonality</strong> (bio15)</p>
<p>xi) <strong>the precipitation of the driest quarter</strong> (bio17)</p>
<p>The is interesting, because the only bioclimatic variables that appear to best explain the distributions of both <em>M. persicae</em> and <em>P. persica</em>, under my modelling approach, are the temperature annual range (bio7), the mean temperature of the wettest quarter (bio8) and the mean temperature of the warmest quarter (bio10). Notably, all other bioclimatic variables are then shared in the two explaantions of the distributions of my two chosen species. To this end, please see the SUPPLEMENTARY MATERIALS at the end of this write-up, for an appreciation of each of the variables. I will return to this point in the future predictions part of my write-up.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/sp2plot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Presence (yellow)/Absence (purple) model with red datapoints for P. persica, across the European range.</figcaption>
</figure>
</div>
</div>
</div>
<p>My map of the current <em>P. persica</em> distribution shows that it is likely to be present throughout much of the UK, Eastern Spain, France, Germany, Western Poland, Italy and Scandinavia. As such, these maps appear to indicate a potential overlap with <em>M. persicae</em>, thus corroborating our biological hypothesis. This therefore warrants further investigation. &nbsp;</p>
</section>
</section>
<section id="distribution-overlap" class="level3">
<h3 class="anchored" data-anchor-id="distribution-overlap"><strong>3: Distribution Overlap</strong></h3>
<section id="the-task-plot-the-overlap-in-distribution-of-the-two-species.-devise-and-calculate-a-metric-for-the-degree-of-overlap-between-their-ranges-explaining-how-you-calculated-it." class="level4">
<h4 class="anchored" data-anchor-id="the-task-plot-the-overlap-in-distribution-of-the-two-species.-devise-and-calculate-a-metric-for-the-degree-of-overlap-between-their-ranges-explaining-how-you-calculated-it.">The task: plot the overlap in distribution of the two species. Devise and calculate a metric for the degree of overlap between their ranges, explaining how you calculated it.</h4>
</section>
<section id="plot-the-overlap-in-distribution-of-the-two-species" class="level4">
<h4 class="anchored" data-anchor-id="plot-the-overlap-in-distribution-of-the-two-species"><u><em>Plot the overlap in distribution of the two species…</em></u></h4>
<p>In order to plot the overlap in distribution between <em>M. persicae</em> and <em>P. persica</em>, I <u>first</u> needed to introduce a buffer distance of 80km, as this is the reputed dispersal capacity of an aphid <span class="citation" data-cites="ahdb2024">(<a href="#ref-ahdb2024" role="doc-biblioref">AHDB 2024</a>)</span>. However, this is a generalisation, and this analysis would be improved by a supplementary study which discovered the dispersal capacity of <em>M. persicae</em> itself.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
An individual aphid can disperse up to 80km!
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="devise-and-calculate-a-metric-for-the-degree-of-overlap-between-their-ranges-explaining-how-you-calculated-it." class="level4">
<h4 class="anchored" data-anchor-id="devise-and-calculate-a-metric-for-the-degree-of-overlap-between-their-ranges-explaining-how-you-calculated-it."><u><em>Devise and calculate a metric for the degree of overlap between their ranges, explaining how you calculated it.</em></u></h4>
<p>In order to devise and calculate a metric for the degree of overlap between the ranges of <em>M. persicae</em> and <em>P. persica</em>, I decided to use the overlap area according to the buffered distribution regions, in order to allow for the mobility of <em>M. persicae</em> to travel. To calculate this, I used the extended expected distribution of species 1, multiplying this by my resampled expected distribution of species 2 (so that the extents matched), to generate a new raster layer. Summing the overlap within this raster layer shows the overlapping distributions of <em>M. persicae</em> and <em>P. persica</em>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/plottingoverlap-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Overlap area (beige) between M. persicae (raw = green), and P. persica (raw = pink), across their European ranges. Associated with a 22882 raster cell overlap.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total overlap area (sum of raster cells): 22882"</code></pre>
</div>
</div>
<p>Ultimately, my map of the overlapping distributions of <em>M. persicae</em> and <em>P. persica</em> shows that there a significant degree of overlap between <em>M. persicae</em> and <em>P. persica</em>. This is quantified as 22882 raster cells, as shown just beneath my overlap plot. Visually, we can perceive that the overlap extends to almost all of the presence datapoints for both species (excluding 2 <em>P. persica</em> points in the East), and extends also to where the points are not plotted, as a result of the buffer.</p>
</section>
</section>
<section id="interspecies-distribution-dependence" class="level3">
<h3 class="anchored" data-anchor-id="interspecies-distribution-dependence"><strong>4: Interspecies Distribution Dependence</strong></h3>
<section id="the-task-use-a-linear-model-to-test-whether-the-distribution-of-species-1-at-the-present-time-depends-on-the-distribution-of-species-2-while-also-taking-account-of-the-effects-of-climatic-variables." class="level4">
<h4 class="anchored" data-anchor-id="the-task-use-a-linear-model-to-test-whether-the-distribution-of-species-1-at-the-present-time-depends-on-the-distribution-of-species-2-while-also-taking-account-of-the-effects-of-climatic-variables.">The task: use a linear model to test whether the distribution of species 1 at the present time depends on the distribution of species 2, while also taking account of the effects of climatic variables.</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pg1_values ~ pg2_values, data = present_overlap_model_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.39081 -0.01629  0.01365  0.01529  0.97038 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.0152879  0.0008131   -18.8   &lt;2e-16 ***
pg2_values   0.4066754  0.0023422   173.6   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1438 on 41826 degrees of freedom
  (23110 observations deleted due to missingness)
Multiple R-squared:  0.4189,    Adjusted R-squared:  0.4189 
F-statistic: 3.015e+04 on 1 and 41826 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Ultimately, this summary of my model shows that there a high degree of statistical signficance between pg2 (which is a proxy for the species distribution of <em>P. persica</em>) and pg1 (which is a proxy for the species distribution of <em>M. persicae</em>), to the degree of &lt;2e-16. This would insinuate that there is a relationship between the distributions of <em>M. persicae</em> and <em>P. persica</em>.</p>
<p>Moreover, approximately 41.5% of pg2 variation is explained by pg1, according to our Adjusted R-Squared. Whilst this is not low, I would not define a 41.5% level of explanation as “dependence” of <em>M. persicae</em> distribution on <em>P. persica</em> without further testing, such as spatial autocorrelation <span class="citation" data-cites="hinch1994">(<a href="#ref-hinch1994" role="doc-biblioref">Hinch 1994</a>)</span>.</p>
</section>
</section>
<section id="future-distribution-prediction" class="level3">
<h3 class="anchored" data-anchor-id="future-distribution-prediction"><strong>5: Future Distribution Prediction</strong></h3>
<section id="the-task-predict-the-future-distribution-of-each-species-using-cmip6-data-for-future-climate-and-predict-how-the-degree-of-overlap-in-ranges-change-will-change-in-that-time.-do-you-expect-the-two-species-to-co-occur-more-often-or-less-often-than-at-the-present" class="level4">
<h4 class="anchored" data-anchor-id="the-task-predict-the-future-distribution-of-each-species-using-cmip6-data-for-future-climate-and-predict-how-the-degree-of-overlap-in-ranges-change-will-change-in-that-time.-do-you-expect-the-two-species-to-co-occur-more-often-or-less-often-than-at-the-present">The task: predict the future distribution of each species using CMIP6 data for future climate and predict how the degree of overlap in ranges change will change in that time. Do you expect the two species to co-occur more often or less often than at the present?</h4>
</section>
<section id="predict-the-future-distribution-of-each-species-using-cmip6-data-for-future-climate" class="level4">
<h4 class="anchored" data-anchor-id="predict-the-future-distribution-of-each-species-using-cmip6-data-for-future-climate"><u><em>Predict the future distribution of each species using CMIP6 data for future climate:</em></u></h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/sp1PvF-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Although subtle, for <em>M. persicae</em>, predicting the future distribution appears to demonstrate a greater presence (as indicated by the yellow end of the spectrum, as per convention) in Northeastern Norway; but a reduced presence (as indicated by the purple end of spectrum) in Southeastern Finland, Southwestern Greece, and Orkney</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Range change metrics:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Current suitable localities: NA"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Future suitable localities: 4"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of new suitable localities (expansion): 0"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of lost suitable localities (contraction): 8"</code></pre>
</div>
</div>
<p>To quantify this, it appears that there will be a small number of future suitable localities, none of which are new (and indicative of distribution expansion), but some will have been lost since the present (which have been lost via distribution contraction). The exact values change upon iterating the model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/plottingsp2PvF-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>With regards to <em>P. persica</em>, the predicted future distribution changes somewhat more drastically. A swathe of yellow presence is predicted across the UK, Scandinavia and mainland Europe.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Range change metrics:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Current suitable localities: NA"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Future suitable localities: 166"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of new suitable localities (expansion): 0"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of lost suitable localities (contraction): 0"</code></pre>
</div>
</div>
<p>This is indicative of 166 future suitable localities; none of these having been lost by contraction from the present. However, none of them have been gained as new by expansion either; which is indicative of the presence simply fortifying in a distribution which P. persica currently occupies.</p>
</section>
<section id="predict-how-the-degree-of-overlap-in-ranges-change" class="level4">
<h4 class="anchored" data-anchor-id="predict-how-the-degree-of-overlap-in-ranges-change"><u><em>Predict how the degree of overlap in ranges change:</em></u></h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total overlap area (sum of raster cells): 23031"</code></pre>
</div>
</div>
<p>To predict how the degree of overlap between M. persicae and P. persica will change under future bioclimatic predictions, I utilised the same overlapping area approach as previously outlined, simply under the new dataset.</p>
</section>
<section id="do-you-expect-the-two-species-to-co-occur-more-often-or-less-often-than-at-the-present" class="level4">
<h4 class="anchored" data-anchor-id="do-you-expect-the-two-species-to-co-occur-more-often-or-less-often-than-at-the-present"><u><em>Do you expect the two species to co-occur more often or less often than at the present?</em></u></h4>
<p>Here, I found the total overlap area, as the sum of the raster cells, to be 23031; an increase from the present day of 22882, but by a percentage increase of just 0.65%. As such, whilst I expect the two species to occur more often under future bioclimates than at present, this increase is very slight.</p>
<p>However, to return to the point I made at the beginning of this analysis, it appears that the distributions of <em>M. persicae</em> and <em>P. persica</em> are deeply entrenched within bioclimatic variables. Both dependent on variables that are both temperature- and precipitation- related, as well as independently associated with all other variables, we might predict that these species’ distributions will react in a complex manner to the uncertain and unfolding future bioclimatic variables (that are illustrated in the SUPPLEMENTARY MATERIALS).</p>
<p>Even without taking into account their ability as biological entities to adapt and evolve, it is extremely hard to predict how such a highly integrated system will change across a generation. However, these modelling efforts are important - and do have implications for stakeholders such as researchers, and also farmers who are economically dependent upon peach cultivation, and their resistance to aphid pests.</p>
</section>
</section>
</section>
<section id="supplementary-materials" class="level2">
<h2 class="anchored" data-anchor-id="supplementary-materials">SUPPLEMENTARY MATERIALS:</h2>
<div class="cell" data-figcap="temperature annual range changes, predicted to affect both M. persicae and P. persicus">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/7change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Temperature is predicted to change within the overlapping species distributions. Perhaps this will affect the species distributions, and their dependence. It has already been shown to be biologically relevant to <em>M. persicae</em> <span class="citation" data-cites="alford2012">(<a href="#ref-alford2012" role="doc-biblioref">Alford 2012</a>)</span>.</p>
<div class="cell" data-figcap="mean temperature of the wettest quarter changes, predicted to affect both M. persicae and P. persicus">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/8change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Mean temperature of the wettest quarter is predicted to change within the overlapping species distributions. Perhaps this will affect the species distributions, and their dependence.</p>
<div class="cell" data-figcap="mean temperature of the warmest quarter changes, predicted to affect both M. persicae and P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/10change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Mean temperature of the warmest quarter is predicted to increase within the overlapping species distributions. Perhaps this will affect the species distributions, and their dependence.</p>
<div class="cell" data-figcap="precipitation seasonality changes, predicted to affect both M. persicae and P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/15change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation seasonality is predicted to change within the overlapping species distributions. Perhaps this will affect the species distributions, and their dependence.</p>
<div class="cell" data-figcap="min temperature of the coldest month changes, predicted to affect M. persicae">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/6change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Min temperature of the coldest month is predicted to increase within the <em>M. persicae</em> distribution. Perhaps this will affect its distribution.</p>
<div class="cell" data-figcap="precipitation of driest month changes, predicted to affect M. persicae">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/14change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation of the driest month is predicted to change within the <em>M. persicae</em> distribution. Perhaps this will affect its distribution.</p>
<div class="cell" data-figcap="precipitation of the wettest quarter changes, predicted to affect M. persicae">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/16change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation of the wettest quarter is predicted to change within the <em>M. persicae</em> distribution. Perhaps this will affect its distribution.</p>
<div class="cell" data-figcap="precipitation of the coldest quarter changes, predicted to affect M. persicae">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/19change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation of the coldest quarter is predicted to change within the <em>M. persicae</em> distribution. Perhaps this will affect its distribution.</p>
<div class="cell" data-figcap="annual mean temperature changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/1change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Annual mean temperature is predicted to increase within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it).</p>
<div class="cell" data-figcap="isothermality changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/3change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Isothermality is predicted to change within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it). It has already shown to be biologically relevant to <em>P. persica</em> <span class="citation" data-cites="bielenberg2022">(<a href="#ref-bielenberg2022" role="doc-biblioref">Bielenberg 2022</a>)</span>.</p>
<div class="cell" data-figcap="mean temperature of the driest quarter changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/9change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Mean temperature of the driest quarter is predicted to change within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it).</p>
<div class="cell" data-figcap="mean temperature of the coldest quarter changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/11change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Mean temperature of the coldest quarter is predicted to increase within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it). It has already been shown to be biologically relevant to <em>P. persica</em> <span class="citation" data-cites="bioscience2021">(<a href="#ref-bioscience2021" role="doc-biblioref">BIOSCIENCE 2021</a>)</span>.</p>
<div class="cell" data-figcap="annual precipitation changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/12change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Annual precipitation is predicted to change within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it). It has already been shown to be biologically relevant to <em>P. persica</em> <span class="citation" data-cites="ighbareyeh2019">(<a href="#ref-ighbareyeh2019" role="doc-biblioref">Ighbareyeh 2019</a>)</span>.</p>
<div class="cell" data-figcap="precipitation of the wettest month changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/13change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation of the wettest month is predicted to change within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it).</p>
<div class="cell" data-figcap="precipitation of driest quarter changes, predicted to affect P. persica">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GeoFinal_files/figure-html/17change-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Precipitation of the driest quarter is predicted to change within the <em>P. persica</em> distribution. Perhaps this will affect its distribution, and consequently the distribution of <em>M. persicae</em> (which is associated with it).</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ahdb2024" class="csl-entry" role="listitem">
AHDB. 2024. <span>“The UK Aphid Monitoring Network.”</span> <a href="https://ahdb.org.uk/knowledge-library/the-uk-aphid-monitoring-network">https://ahdb.org.uk/knowledge-library/the-uk-aphid-monitoring-network</a>.
</div>
<div id="ref-alford2012" class="csl-entry" role="listitem">
Alford, Lucy. 2012. <span>“Effect of Latitude and Acclimation on the Lethal Temperatures of the Peach-Potato Aphid Myzus Persicae.”</span> <em>Agricultural and Forest Entomology</em>, February, 1–13. <a href="https://doi.org/10.1111/j.1461-9563.2011.00553.x">https://doi.org/10.1111/j.1461-9563.2011.00553.x</a>.
</div>
<div id="ref-bielenberg2022" class="csl-entry" role="listitem">
Bielenberg, Douglas, G.,. 2022. <span>“Peach [Prunus Persica (l.) Batsch] Cultivars Differ in Apparent Base Temperature and Growing Degree Hour Requirement for Floral Bud Break.”</span> <em>Frontiers in Plant Science</em> 13 (1): 1–10. <a href="https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2022.801606/full">https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2022.801606/full</a>.
</div>
<div id="ref-bioscience2021" class="csl-entry" role="listitem">
BIOSCIENCE, FUTURECO. 2021. <span>“Genes Underpinning Peach Tree Adaptation to Climate Change.”</span> <em>FUTURECO BIOSCIENCE</em>, July, 1. <a href="https://www.futurecobioscience.com/en/genes-que-sustentan-la-adaptacion-del-melocotonero-al-cambio-climatico/">https://www.futurecobioscience.com/en/genes-que-sustentan-la-adaptacion-del-melocotonero-al-cambio-climatico/</a>.
</div>
<div id="ref-clim" class="csl-entry" role="listitem">
Clim, World. n.d. <span>“Bioclimatic Variables.”</span>
</div>
<div id="ref-hinch1994" class="csl-entry" role="listitem">
Hinch, Scott. 1994. <span>“Spatial Autocorrelation and Assessment of Habitat<span></span>abundance Relationships in Littoral Zone Fish.”</span> <em>Canadian Science Publishing</em> 51 (3): 701–12. <a href="https://doi.org/10.1139/f94-070">https://doi.org/10.1139/f94-070</a>.
</div>
<div id="ref-ighbareyeh2019" class="csl-entry" role="listitem">
Ighbareyeh, Jehad, M., H. 2019. <span>“Peach (Prunus Persica l. Batsch) Production and Environmental Conditions in Jenin, Palestine.”</span> <em>Netjournals</em>, May, 78–84. <a href="https://www.netjournals.org/pdf/NJAS/2019/2/19-025.pdf">https://www.netjournals.org/pdf/NJAS/2019/2/19-025.pdf</a>.
</div>
<div id="ref-odoherty1985" class="csl-entry" role="listitem">
O’Doherty, Rose. 1985. <span>“Studies on the Cold Hardiness of the Peach-Potato Aphid Myzus Persicae (Sulzer).”</span> <em>White Rose eTheses</em> 1 (1): 1–20. <a href="https://etheses.whiterose.ac.uk/id/eprint/4413/1/uk_bl_ethos_354043.pdf">https://etheses.whiterose.ac.uk/id/eprint/4413/1/uk_bl_ethos_354043.pdf</a>.
</div>
<div id="ref-verdugo2016" class="csl-entry" role="listitem">
Verdugo, Jaime, A. 2016. <span>“A Review on the Complexity of Insect-Plant Interactions Under Varying Levels of Resources and Host Resistance: The Case of Myzus Persicae-Prunus Persica.”</span> <em>Biotechnologie, Agronomie, Société Et Environnement/Biotechnology, Agronomy, Society and Environment</em> 20 (4). <a href="https://doi.org/10.25518/1780-4507.13218">https://doi.org/10.25518/1780-4507.13218</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>